spring:
  application:
    name: hello-git
  # config:
  #   import: optional:configserver:http://localhost:7000
server:
  port: 3000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
